# Generated by Django 4.2.27 on 2026-02-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CatBreed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("origin", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "health_info",
                    models.TextField(
                        help_text="Common health issues and life expectancy"
                    ),
                ),
                (
                    "habits",
                    models.TextField(help_text="Behavioral traits and temperament"),
                ),
                (
                    "food_recommendations",
                    models.TextField(help_text="Dietary needs and recommendations"),
                ),
            ],
        ),
    ]
